### ISSUE TITLE
Refering pages

### ISSUE THREAD

**Issue by bbert** [KnodesCommunity/typedoc-plugins#198]
### Plugin

@knodes/typedoc-plugin-pages

### Typedoc plugin(s) version(s)

@knodes/typedoc-plugin-pages@0.23.1

### Typedoc version

0.23.15

### Describe the problem

I was previously using typedoc-plugin-pages and refering pages seems not working or differently.
Before:
```
{@page <page title>}
```
Now:
```
{@page <path-to-file>}
```

Question: how do we refer pages from within the source code?
I tried different solutions to refer .md files but unsuccessfully

### What did you expected ?

Be able to refer pages based on pages titles, from md files and from source code

**Comment by GerkinDev** [comment]
Hi,

Referencng pages is done either via relative paths (starting with `./` or `../`, like `{@page ../foo.md}` or via their paths relative to the pages root folder, thus, you should omit it.

I can't really diagnose the issue you have because it seems that you didn't properly code-fenced the syntax you use.

I would be pleased to have some kind of repro in order to check this out for the next release.

**Comment by GerkinDev** [comment]
Hi, did you make it work or still need help ?

**Comment by bbert** [comment]
Hi, sorry but I did change job/position and I cannot test anymore

**Comment by GerkinDev** [comment]
Alright; since this is a usage question, I close the issue for housekeeping purposes
